### ISSUE TITLE
SDS - Expose to API key in header-value

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/spine-directory-service-api#78]
While sending the request, we are passing the apikey in header and its value is getting exposed.

Steps to reproduce - 
Send GET:  https://int.api.service.nhs.uk/spine-directory/Endpoint
Query Parameters -  org-code -YGMYH and service-id - eg. urn:nhs:names:services:gp2gp:COPC_IN000001UK01
Header - apikey - myG6cYQthVUzGeA0sHcCVPp3aSSZItF3

Expected Result- apikey should not be exposed
Actual Result - apikey is displayed in each request.

**Comment by michael-kainos** [comment]
@sonalnegivarma where is the apikey exposed?

**Comment by sonalnegivarma** [comment]
we are passing api key in request headers for authentication against SDS API endpoint

**Comment by sonalnegivarma** [comment]
SDS api authenticated with APi key only.When using postman it is visible to us.When you integrate SDS with product it can be passed as secret.
