### ISSUE TITLE
Passing invalid and empty org-code value is giving 500 internal server error

### ISSUE THREAD

**Issue by sonalnegivarma** [NHSDigital/spine-directory-service-api#81]
1 ) Send invalid org-code value
2) Send request with empty org-code value

URL - GET: https://int.api.service.nhs.uk/spine-directory/Endpoint
Query Parameter -  org-code - Pass invalid org-code or empty org-code value
service-id - urn:nhs:names:services:pds:RCMR_IN010000UK05
apikey - myG6cYQthVUzGeA0sHqCVPp3aSSZItF3

Actual Response - 500 internal server error
Expected Response - 400 bad request or 404 not found

**Comment by davesmith9088** [comment]
This also happens if the org code is valid but isn't found in the directory - it should return a 404

**Comment by michael-kainos** [comment]
This will be fixed in sprint 19

**Comment by michael-kainos** [comment]
@sonalnegivarma  @davesmith9088 Based on the FHIR profile this scenario should be an empty bundle. 404 will not be added. Will close this and this can be verified by @davesmith9088 once this is changed in sprint 20. @sonalnegivarma please  keep this outlined in the test report and i will pass this information to NHSD that they sign off the report based on Meddbase verifying the change in sprint 20
